name: Prettier Format Check

on:
    push: 
    pull_request: 

jobs:
    prettier-check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                version: 20

            - name: Install dependencies
              run: npm install

            - name: Run Prettier Check
              run: npm run format:check

            
    
